export default {
    CHANGE_PATH: 'CHANGE_PATH',
    SET_CONTENTS: 'SET_CONTENTS',
    OPEN_FOLDER: 'OPEN_FOLDER',
    GO_TO_PARENT_FOLDER: 'GO_TO_PARENT_FOLDER',

    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    RENAME_FAVORITE: 'RENAME_FAVORITE',
    LOAD_FAVORITES: 'LOAD_FAVORITES',
    
    STORE_STATE_IN_FILE: 'STORE_STATE_IN_FILE',
    LOAD_STATE_FROM_FILE: 'LOAD_STATE_FROM_FILE',

    SWITCH_TAB: 'SWITCH_TAB',
    CLOSE_TAB: 'CLOSE_TAB',
    NEW_TAB: 'NEW_TAB',

    MINIMIZE_WINDOW: 'MINIMIZE_WINDOW',
    TOGGLE_MAXIMIZE_WINDOW: 'TOGGLE_MAXIMIZE_WINDOW',
    CLOSE_WINDOW: 'CLOSE_WINDOW'
}