export default {
    CHANGE_PATH: 'CHANGE_PATH',
    SET_CONTENTS: 'SET_CONTENTS',
    GO_TO_PARENT_FOLDER: 'GO_TO_PARENT_FOLDER',
    OPEN_FOLDER: 'OPEN_FOLDER',
    OPEN_FILE: 'OPEN_FILE',
    
    SELECT_ITEM: 'SELECT_ITEM',
    CLEAR_SELECTION: 'CLEAR_SELECTION',
    
    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    RENAME_FAVORITE: 'RENAME_FAVORITE',
    LOAD_FAVORITES: 'LOAD_FAVORITES',
    
    STORE_STATE_IN_FILE: 'STORE_STATE_IN_FILE',
    LOAD_STATE_FROM_FILE: 'LOAD_STATE_FROM_FILE',

    SWITCH_TAB: 'SWITCH_TAB',
    CLOSE_TAB: 'CLOSE_TAB',
    NEW_TAB: 'NEW_TAB',
    NEXT_TAB: 'NEXT_TAB',
    PREVIOUS_TAB: 'PREVIOUS_TAB',

    MINIMIZE_WINDOW: 'MINIMIZE_WINDOW',
    TOGGLE_MAXIMIZE_WINDOW: 'TOGGLE_MAXIMIZE_WINDOW',
    CLOSE_WINDOW: 'CLOSE_WINDOW',
    COPY_TO_STAGING_AREA: 'COPY_TO_STAGING_AREA',
    CUT_TO_STAGING_AREA: 'CUT_TO_STAGING_AREA',
    REMOVE_FROM_STAGING_AREA: 'REMOVE_FROM_STAGING_AREA',
    PASTE_FROM_STAGING_AREA: 'PASTE_FROM_STAGING_AREA',
    TRANSFER_COMPLETE: 'TRANSFER_COMPLETE',

    CTRL_X: 'CTRL_X',
    CTRL_C: 'CTRL_C',
    CTRL_V: 'CTRL_V',
    DELETE: 'DELETE',

    TOGGLE_PROPERTIES: 'TOGGLE_PROPERTIES',
    TOGGLE_FAVORITES: 'TOGGLE_FAVORITES'
}