export default {
    CHANGE_PATH: 'CHANGE_PATH',
    SET_FILES_LIST: 'SET_FILES_LIST',
    OPEN_FOLDER: 'OPEN_FOLDER',
    GO_TO_PARENT_FOLDER: 'GO_TO_PARENT_FOLDER',

    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    RENAME_FAVORITE: 'RENAME_FAVORITE'
}